# Generated by Django 6.1.1 on 2026-09-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='fechas_tentativas',
            field=models.DateField(blank=True, null=True),
        ),
    ]
